### PR TITLE
Revert "ARM OSX Migrator"

### PR DESCRIPTION
**Pull request by sarthakpati**
Reverts conda-forge/tiffslide-feedstock#11

### CODE REVIEW

**Comment by ap--** [comment]
Okay, so while it's unfortunate that these osx arm packages were released, without being tested well (or at least I think so), it revealed another issue:

why is the tiffslide package not labeled as `noarch`?

After all, it's pure python. And had no binary modules...

Let's close this PR, and add noarch as label to the new tiffslide release.

**Comment by ap--** [comment]
In case the arm packages will turn out later to be broken, we should remember to mark them.

**Comment by sarthakpati** [comment]
Thanks @ap-- and once again, apologies for the confusion I created. I'll be more careful next time.

**Comment by ap--** [comment]
No worries! :smiley: 
I think once we move to noarch this shouldn't be an issue at all.
And we'll save a lot of ci compute time. So win-win :heart:

**Pull request closed without merging**
